server:
  port: 8080
  debugPort: 30020
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: excel
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      charset: utf-8
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: test
axon:
  distributed:
    enabled: false
    spring-cloud:
      fallback-url: /message-routing-information
      fallback-to-http-get: true
#eureka:
#  instance:
#    hostname: 127.0.0.1
#  client:
#    healthcheck:
#      enabled: true
##    register-with-eureka: true
##    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:30003/eureka/